export const UPD_FIELD = 'UPD_FIELD'

export const CHANGE_RATE = 'CHANGE_RATE'
export const CHANGE_BALANCE = 'CHANGE_BALANCE'

export const RESET_WIN = 'RESET_WIN'
export const START_SPIN = 'START_SPIN'
export const STOP_SPIN_FIRST_COLUMN = 'STOP_SPIN_FIRST_COLUMN'
export const STOP_SPIN_SECOND_COLUMN = 'STOP_SPIN_SECOND_COLUMN'
export const STOP_SPIN_THIRD_COLUMN = 'STOP_SPIN_THIRD_COLUMN'

export const SET_WIN = 'SET_WIN'
export const CHANGE_LAST_PRIZE = 'CHANGE_LAST_PRIZE'
export const SHOW_MODAL_PRIZE = 'SHOW_MODAL_PRIZE'
export const HIDE_MODAL_PRIZE = 'HIDE_MODAL_PRIZE'

export const PLAY_FIRST_STOP_SOUND = 'PLAY_FIRST_STOP_SOUND'
export const PLAY_SECOND_STOP_SOUND = 'PLAY_SECOND_STOP_SOUND'
export const PLAY_THIRD_STOP_SOUND = 'PLAY_THIRD_STOP_SOUND'
export const RESET_STOP_SOUNDS = 'RESET_STOP_SOUNDS'
export const PLAY_BONUS_SOUND = 'PLAY_BONUS_SOUND'
export const STOP_BONUS_SOUND = 'STOP_BONUS_SOUND'